nome = input('digite seu nome \n')
dia = input('digite o dia de seu nascimento\n')
mes = input('digite o mês de seu nascimento\n')
ano = input('digite o ano de seu nascimento\n')
print('vc nasceu em: '+dia+'/'+mes+'/'+ano)
